---

- name: collect outputs after config 
  hosts: all
  gather_facts: no
  connection: network_cli
  vars_files:
    - "group_vars/overlay_db.yml"

  tasks:  

          - name: Construct show commands from host var file for leafs
            when: inventory_hostname in groups['leaf'] | default([])
            copy:
              dest: "output/{{inventory_hostname}}-show_commands.txt" 
              content: "{{ lookup('template', '../templates/leaf_show_command.j2') }}"

          - name: Construct show commands from host var file for Spines
            when: inventory_hostname in groups['spine'] | default([])
            copy:
              dest: "output/{{inventory_hostname}}-show_commands.txt" 
              content: "{{ lookup('template', '../templates/spine_show_command.j2') }}"

          - name: Cat show commands file
            shell: cat "output/{{inventory_hostname}}-show_commands.txt"
            register: command_buf

          - name: Run show command
            ios_command:
              commands:
                "{{ command_buf.stdout_lines }}" 
            register: dev_output

          - name: Save outputs to output file
            copy:
              dest: "output/{{inventory_hostname}}-show_output.txt" 
              content: |
                "{{ command_buf.stdout_lines | zip(dev_output.stdout_lines) | to_nice_yaml}}" 

          - name: Display output file info
            run_once: true
            debug:
              msg: 
              - Please refer to <hostname>-show_commands.txt  in 'output' folder
              - Please refer to <hostname>-show_output.txt in 'output' folder
