---

- name: Automated VXLAN deployment with BGP EVPN L2/L3 underlay w/ Spine
  hosts: leaf
  gather_facts: no
  vars:
    playbook_mode: ""
    intf_conf_list: []
    access_block: ""
    
  tasks:

          - name: Collect VLANs from overlay_db
            when: playbook_mode == ''
            run_once: true
            block:
            - set_fact:
                host_vars_path: '{{ playbook_dir }}'
            
            - name: Collect vars from overlay_db.yml
              include_vars: 
                file: "./group_vars/overlay_db.yml"
                name: overlay_db_vars

            - name: Get access-side VLANs
              set_fact: 
                access_side_vlans: "{{ (access_side_vlans | default([])) + [ item ] }}"
              when: overlay_db_vars['vlans'][item]['vlan_type'] == 'access'
              loop: "{{ overlay_db_vars.vlans.keys() }}"  

          # host_vars_path is respective folder (dag, l2vni, l3vni) when imported in overlay_incremental playbook
          - name: Load variables from host_vars/access_intf/<hostname>.yml if present
            block:
            - name: Check whether host_vars/access_intf/<hostname>.yml is present
              local_action: stat path="{{ host_vars_path }}/host_vars/access_intf/{{ inventory_hostname }}.yml"
              register: acc_file_state
              become: no 
              
            - name: Load vars from host_vars/access_intf/<hostname>.yml
              include_vars:
                file: "{{ host_vars_path }}/host_vars/access_intf/{{ inventory_hostname }}.yml"
                name: access_intf_vars
              when: acc_file_state.stat.exists

          # Following tasks are skippped if host_vars/access_intf/<hostname>.yml is not present

          - name: Process interfaces
            when: (access_intf_vars is defined) and (access_intf_vars.access_interfaces is defined)
            block:
            - name: Process access interfaces data
              access_intf_preprocess:
                access_interfaces: "{{ access_intf_vars.access_interfaces }}"
                vlan_overlay_db: "{{ access_side_vlans | default([]) }}"
              register: access_intf_output

            - name: Call Cisco L2 interface module for trunk interfaces
              cisco.ios.ios_l2_interfaces:
                config:
                - name: "{{ intf_dict.name }}"
                  mode: trunk
                  trunk:
                    allowed_vlans: "{{ intf_dict.vlans }}"
                state: rendered
              register: trunk_unit
              loop: "{{ access_intf_output.trunks | default([]) }}"
              loop_control:
                loop_var: intf_dict

            - name: Call Cisco L2 interface module for access interfaces
              when: playbook_mode == ''
              cisco.ios.ios_l2_interfaces:
                config:
                - name: "{{ intf_dict.name }}"
                  mode: access
                  access:
                    vlan: "{{ intf_dict.vlans }}"
                state: rendered
              register: access_unit
              loop: "{{ access_intf_output.access | default([]) }}"
              loop_control:
                loop_var: intf_dict

            - name: Join trunk and acess interface configs
              set_fact:
                intf_unit: "{{ (trunk_unit.results | default([])) + (access_unit.results | default([])) }}"
                
            - name: Add 'no shut' to the interfaces
              set_fact:
                intf_conf_list: "{{ intf_conf_list + item.rendered + [item.rendered[0]] + ['no shut'] }}"
              when: item.rendered is defined
              loop: "{{ intf_unit }}"

            - set_fact:
                access_block: "\n! Access interface block \n{{ intf_conf_list | join('\n') }}"

          - name: Copy configurations to respective file (<hostname>-intf.txt ) under 'preview_files' folder
            when: playbook_mode == ""
            copy:
              dest: preview_files/{{inventory_hostname}}{{ playbook_mode }}-intf.txt
              content: "{{ access_block }}"

          - name: Copy configurations to respective file ( <hostname>-inc.txt ) under 'preview_files' folder
            when: playbook_mode == "-inc"
            lineinfile:
              dest: preview_files/{{inventory_hostname}}{{ playbook_mode }}.txt
              insertafter: EOF
              line: "{{ access_block }}"

- name: Display preview file info
  hosts: localhost
  gather_facts: no
  vars:
    playbook_mode: ""

  tasks:
            - debug:
                msg: Please refer to <hostname>{{ playbook_mode }}-intf.txt in 'preview_files' folder
              when: playbook_mode == ""
