---

- name: Enable DHCP for EVPN overlay
  hosts: leaf
  gather_facts: no
  vars:
    playbook_mode: ""
    template_list:
      - '../templates/dhcp_overlay.j2'

  tasks:
            - name: Load and process DHCP input file
              run_once: true
              when: playbook_mode == ""
              block:
              - name: Load vars from dhcp_db.yml
                include_vars: 
                  file: "./group_vars/dhcp_db.yml"
                  name: dhcp_db_vars

              - set_fact:
                  vrfs: "{{ dhcp_db_vars.dag }}"
                  dhcp_options: "{{ dhcp_db_vars.dhcp_options | default({}) }}"
                  
            - name: Collect VRFs with no relay interface set if any
              run_once: true
              dhcp_preprocess:
                dhcp_vars: "{{ vrfs }}"
              register: no_src_vrfs
                
            # Collect VRFs, SVIs and overlay interfaces data
            - name: Run and parse show run nve
              ansible.utils.cli_parse:
                command: "show run nve"
                parser:
                  name: ansible.netcommon.pyats
                set_fact: overlay_dict

            - name: Get VRFs (if 'all'), SVIs and relay src interface (if not defined already)
              dhcp_preprocess:
                overlay_dict: "{{ overlay_dict | combine({'no_src_vrfs':no_src_vrfs.vrfs, 'dhcp_vars':vrfs}) }}"
              register: module_output

            - name: Include VRFs, SVIs and source interfaces dict from module output
              set_fact:
                "{{ item.key }}": "{{ item.value }}"
              with_dict: "{{ module_output }}"

            - name: Apply configurations
              cli_config:
                config: "{{ lookup('template', item) }}"
                diff_match: none 
              register: result
              loop: "{{ template_list }}"
