---

- name: Automated VXLAN deployment with BGP EVPN L2/L3 underlay w/ Spine
  hosts: all
  gather_facts: no
  vars: 
    overlay_block: ""
    leaf_template_list:
      - '../templates/vrf_definition.j2'
      - '../templates/bgp_l2vpn_ipv46_per_vrf.j2'
      - '../templates/vlan_create.j2'
      - '../templates/svi_create.j2'
      - '../templates/l2vpn_evpn_global.j2'
      - '../templates/l2vpn_evpn_evi_create.j2'
      - '../templates/evi_vni_vlan_stiching.j2'
      - '../templates/overlay_interfaces.j2'
      - '../templates/nve_create.j2'

    common_template_list:
      - '../templates/bgp_global.j2'
      - '../templates/bgp_l2vpn_evpn_af.j2'

  tasks:

          - name: Load vars from group_vars/overlay_db.yml
            run_once: true
            include_vars: 
              file: "./group_vars/overlay_db.yml"

          - name: Load vars from host_vars/node_vars/<hostname>.yml
            include_vars: 
              file: "./host_vars/node_vars/{{ inventory_hostname }}.yml"

          - name: Read overlay template files
            set_fact:
              overlay_block: "{{ overlay_block }}{{ lookup('template', item) }}"
            loop: "{{ common_template_list }}"

          - name: Read overlay template files specific to leaf
            when: inventory_hostname in (groups['leaf'] | default([]))
            set_fact:
              overlay_block: "{{ overlay_block }}{{ lookup('template', item) }}"
            loop: "{{ leaf_template_list }}"

          - name: Copy configurations to respective file ( <hostname>-overlay.txt ) under 'preview_files' folder
            copy:
              dest: preview_files/{{inventory_hostname}}-overlay.txt
              content: "{{ overlay_block | regex_replace('#jinja2: lstrip_blocks: \"True\", trim_blocks: \"True\"', '') | regex_replace('\\n(\\s+)','\n') | regex_replace('! ','\n\n! ') }}"

- name: Display preview file info
  hosts: localhost
  gather_facts: no

  tasks:
          - debug:
              msg: Please refer to <hostname>-overlay.txt in 'preview_files' folder
