---

- name: Overlay "group_vars/overlay_db.yml" validation 
  hosts: all 
  gather_facts: no


  tasks:

        - block:

          - name: Set playbook name and mode
            set_fact:
              playbook_name: "yml_validation"
              playbook_mode: ""

          - name: Run the "group_vars/overlay_db.yml" validation module
            run_once: true
            precheck_l3vni_yml: 
              fileName: "group_vars/overlay_db.yml"
              #debug : 'verbose'( displaying complete output if validation is successful else displays the errors)
              #debug : ' '(displays only error senarios if found any)
              debug : ''
            register: result
            
          - name: Print result
            run_once: true
            debug:
              msg: "Yaml file validation : {{ result}}'"

          rescue:
            - name: Record failure
              include_tasks: ../subtasks/common_subtasks/subtask_rescue_task.yml


- name: Display output file info
  hosts: localhost
  gather_facts: no
  run_once: True

  tasks:
    - debug:
        msg: 
        - "Please refer the following folders/files"
        - "'yml_validation-err.log' in 'log_directory' folder for error informations if any"
