---

- name: Overlay "group_vars/overlay_db.yml" validation 
  hosts: all 
  gather_facts: no
  tasks:  
          - name: run the "group_vars/overlay_db.yml" validation module
            run_once: true
            precheck_l3vni_yml: 
              fileName: "group_vars/overlay_db.yml"
              #debug : 'verbose'( displaying complete output if validation is successful else displays the errors)
              #debug : ' '(displays only error senarios if found any)
              debug : ''
            register: result
            
          - name: Print result
            run_once: true
            debug:
              msg: "Yaml file validation : {{ result}}'"
