---

- name: Automated VXLAN deployment with BGP EVPN L3 underlay w/ Spine
  hosts: leaf
  gather_facts: no 
  tasks:
          - name: Locate files in host_vars/ipv6_delete_vars dir
            find:
              path: "host_vars/ipv6_delete_vars"
            register: cleanup
            ignore_errors: true
          
          - name: Remove files from previous run
            file:
              path: "{{ item.path }}"
              state: absent
            with_items: "{{ cleanup.files }}"
            ignore_errors: true
              
          - name: Collect vars from overlay_db.yml
            run_once: true
            include_vars:
              file: group_vars/overlay_db.yml
              name: to_compare
          
          - name: Collect vars from ipv6_delete_vars.yml
            run_once: true
            include_vars:
              file: group_vars/ipv6_delete_vars.yml
              name: user_input

          - name: Collect "show run nve"
            cli_command:
              command: show run nve
            register: command_output
            
          - name: Collect vars from hostvars leafs
            run_once: true
            include_vars:
              file: host_vars/node_vars/{{ inventory_hostname }}.yml
              name: hostvars_leaf_data
                
          - name: Process data
            delete_ipv6_l3vni:
              hostvars: "{{ command_output.stdout_lines }}"
              leaf_data:  "{{ hostvars_leaf_data }}"
              overlay_db: "{{ to_compare }}"
              userinput: "{{ user_input }}"
            register: module_output
              
          - name: Copying configurations to the repective files ( <hostname>.yml ) under host_vars/ipv6_delete_vars folder
            when: module_output['yaml'] != '{}\n'
            copy:
              dest: host_vars/ipv6_delete_vars/{{ inventory_hostname }}.yml
              content: "{{ module_output['yaml'] }}"
