---

- name: collect outputs after config 
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:  

          - name: construct show commands from host var file for leafs
            when: inventory_hostname in groups['leaf']
            copy:
                dest: "output/{{inventory_hostname}}-show_commands.txt" 
                content: "{{ lookup('template', '../templates/leaf_show_command.j2') }}"

          - name: cat show commands file of leaf
            when: inventory_hostname in groups['leaf']
            shell: cat "output/{{inventory_hostname}}-show_commands.txt"
            register: leaf_command_buf
            
          - name: run show command on Leafs
            when: inventory_hostname in groups['leaf']
            ios_command:
               commands:
                   "{{ leaf_command_buf.stdout_lines }}" 

            register: leaf_output

          - name: save outputs to output file for Leafs
            when: inventory_hostname in groups['leaf']
            copy:
                dest: "output/{{inventory_hostname}}-show_output.txt" 
                content: |
                  "{{leaf_command_buf.stdout_lines | zip(leaf_output.stdout_lines) | to_nice_yaml}}"   

          - name: construct show commands from host var file for Spines
            when: inventory_hostname in groups['spine']
            copy:
                dest: "output/{{inventory_hostname}}-show_commands.txt" 
                content: "{{ lookup('template', '../templates/spine_show_command.j2') }}"

          - name: cat show commands file of Spines
            when: inventory_hostname in groups['spine']
            shell: cat "output/{{inventory_hostname}}-show_commands.txt"
            register: spine_command_buf
            
          - name: run show command on Spines
            when: inventory_hostname in groups['spine']
            ios_command:
               commands:
                   "{{ spine_command_buf.stdout_lines }}" 

            register: spine_output

          - name: save outputs to output file for Spines
            when: inventory_hostname in groups['spine']
            copy:
                dest: "output/{{inventory_hostname}}-show_output.txt" 
                content: |
                  "{{spine_command_buf.stdout_lines | zip(spine_output.stdout_lines) | to_nice_yaml}}"   


