---

- name: Automated VXLAN deployment with BGP EVPN L3 underlay w/ Spine
  hosts: leaf
  gather_facts: no 

  tasks:

          - name: Cleanup host_vars/inc_vars dir
            run_once: true
            file:
              state: "{{ item }}"
              path: "host_vars/inc_vars"
            with_items:
              - absent
              - directory

          - name: Collect vars from create_vars.yml
            run_once: true
            include_vars:
              file: group_vars/create_vars.yml
              name: user_input
              
          - name: Collect vars from overlay_db.yml
            run_once: true
            include_vars:
              file: group_vars/overlay_db.yml
              name: to_compare
          
          - name: Collect vars from hostvars leafs
            run_once: true
            include_vars:
              file: host_vars/node_vars/{{ inventory_hostname }}.yml
              name: hostvars_leaf_data

          - name: Collect "show run nve"
            cli_command:
              command: show run nve
            register: command_output
                
          - name: Process data
            create_incremental_l3vni_yml:
              userinput: "{{ user_input }}"
              overlay_intf:  "{{ hostvars_leaf_data }}"
              hostvars: "{{ command_output.stdout_lines }}"
              tocompare: "{{ to_compare }}"
            register: module_output
              
          - name: Copying configurations to the repective files ( <hostname>.yml ) under host_vars/inc_vars folder
            when: module_output['yaml'] != '{}\n'
            copy:
              dest: host_vars/inc_vars/{{ inventory_hostname }}.yml
              content: "{{ module_output['yaml'] }}"
