# This is the input file for playbook_overlay_delete_preview.yml and playbook_overlay_delete_commit.yml
#
# List the DAG/s to be deleted under 'dag' keyword
# The keyword 'update_access' when set to true removes the related VLANs from the interfaces
#
#
# ______________________________________________
# __________ EXAMPLE SCENARIOS _________________
# ______________________________________________
#
# Example 1: Deletes blue and green DAGs and removes the respective VLANs from the access interfaces
# 
#   dag:
#      - blue             <--------- deletes blue and green DAGs
#      - green
#
#   update_access: true   <--------- removes the respective VLANs from the access interfaces
#
#
# Example 2: Deletes all the DAGs and makes NO changes to the access interfaces
#
#   dag:
#      - all               <--------- deletes all the DAGs
# 
#   update_access: false   <--------- makes NO changes to the access interfaces
#
# ______________________________________________
# ______________________________________________
# ______________________________________________


 dag:
    - blue

 update_access: true
