# ipv6_incremental:
# ==================
# ipv6_action can be performed for both 'add' or 'delete' with the help of playbook_overlay_incremental_ipv6_commit.py
#Please find below the examples of declaring the respective dag's for ipv6_incremental
# 1) with single dag and action "add"
#      ..........................................
#      .        dag:              .
#      .          orange:                       .
#      .            ipv6_action : 'add'      .
#      ..........................................
# 2) with two dag's and action "add"
#      ..........................................
#      .        dag:              .
#      .          red:                       .
#      .            ipv6_action : 'add'      .
#      .          orange:                       .
#      .            ipv6_action : 'add'      .
#      ..........................................
# 3) with single dag and action "delete"
#      ..........................................
#      .        dag:              .
#      .          orange:                       .
#      .            ipv6_action : 'delete'      .
#      ..........................................
# 4) with two dag's and action "delete"
#      ..........................................
#      .        dag:              .
#      .          red:                       .
#      .            ipv6_action : 'delete'      .
#      .          orange:                       .
#      .            ipv6_action : 'delete'      .
#      ..........................................
dag:
   white : 
     ipv6_action : 'add'
   

