---
  
- name: Automated VXLAN deployment with BGP EVPN L2/L3 underlay w/ Spine
  hosts: leaf
  gather_facts: no

  vars:
    action : 'delete'

    leaf_auth_dict:
      '../templates/auth_configs.j2': 'auth configs block'
      '../templates/aaa_configs.j2': 'aaa configs block'


  tasks:

        - block:

          - name: Set playbook name and mode
            set_fact:
              playbook_name: "auth"
              playbook_mode: "-del"

          - name: Load vars from auth_db input file
            run_once: true
            include_vars: 
              file: "group_vars/auth_db.yml"
          
#          - name: run command expecting user confirmation
#            cli_command:
#              command: "{{ item }}"
#              prompt:
#                - "This operation will remove all username related configurations with same name.Do you want to continue? [confirm]"
#              answer: 'y'
#            loop:
#              - conf t
#              - no username user1 privilege 15 password 0 Cisco123
                      
          - name: aaa and auth configuration
            when: (inventory_hostname in groups['leaf']) 
            cli_config:
              config: " {{ lookup('template', item.key) }} "
              diff_match: none
            register: result
            with_dict: "{{ leaf_auth_dict }}"
            become: yes

          rescue:
            - name: Record failure
              include_tasks: ../subtasks/common_subtasks/subtask_rescue_task.yml

- name: Display output file info
  hosts: leaf
  gather_facts: no
  run_once: True

  tasks:
    - debug:
        msg: 
        - "Please refer the following folders/files"
        - "'auth-del-err.log' in 'log_directory' folder for error informations if any"
