---

- name: Initialising variable for leaf-s
  hosts: leaf
  gather_facts: no
  tasks:    
          - set_fact:
              playbook_mode: '-inc'

- name: Import tasks from playbook_access_add_commit.yml
  import_playbook: playbook_access_add_commit.yml
