---

- name: Automated VXLAN deployment with BGP EVPN L2/L3 underlay w/ Spine
  hosts: all
  gather_facts: no

  vars:
    input_vars_path: "./"
    underlay_block: ""

    underlay_general_dict:
      '../templates/hostname.j2': 'hostname block'
      '../templates/global_routing.j2': 'global routing block'
      '../templates/pim_rp.j2': 'pim rp block'

    underlay_intf_dict:
      '../templates/underlay_interfaces.j2': 'underlay interface block'
      '../templates/ospf_interfaces.j2': 'ospf interface block' # divide it?
      '../templates/pim_interfaces.j2': 'pim interface block'

    underlay_intf_new_node_dict:
      '../templates/underlay_interfaces.j2': 'underlay interface block'
      '../templates/ospf_interfaces_only.j2': 'ospf interface block' # divide it?
      '../templates/pim_interfaces.j2': 'pim interface block'

    underlay_msdp_dict:
      '../templates/msdp_peering.j2': 'MSDP peering block'

    underlay_leaf_dict: "{{ underlay_general_dict | combine( underlay_intf_dict )}}"

    underlay_spine_dict: "{{ underlay_leaf_dict | combine( underlay_msdp_dict )}}"

    underlay_borderspine_dict: "{{ underlay_msdp_dict }}"


  tasks:

        - block:

          - name: Set playbook name and mode
            set_fact:
              playbook_name: "underlay"
              playbook_mode: ""

          # leaf_group, borderspine_group, spine_group and new_node are defined in subtask
          - name: Get inventory groups
            include_tasks: ../subtasks/common_subtasks/subtask_get_inventory_group.yml
          
          - name: Load vars from group_vars/underlay_config file
            run_once: true
            include_vars:
              file: "{{ input_vars_path }}group_vars/underlay_config.yml"           

          - name: Load variables from node_vars/<host>.yml input file
            when: inventory_hostname in leaf_group + spine_group
            include_vars: 
              file: "{{ input_vars_path }}host_vars/node_vars/{{ inventory_hostname }}.yml"

          - name: Update dictionary to enable routing for ipv4 unicast
            set_fact:
              routing: "{{ routing | default({}) | combine( {'ipv4_uni': 'yes'} ) }}"

          - name: Load vars from overlay input file
            run_once: true
            include_vars: 
              file: "{{ input_vars_path }}group_vars/overlay_db.yml"

          # --------- This task runs only when new leaf/s are added in incr_inventory.yml ---------
          - name: Tasks for new leaf addition
            when: new_node == true
            include_tasks: ../subtasks/underlay_subtasks/subtask_new_node_tasks.yml
          # ---------------------------------------------------------------------------------------

          - name: Read template files for leaf devices
            when: inventory_hostname in leaf_group      # leaf_group includes borderspine
            set_fact:
              underlay_block: "{{ underlay_block }} ! {{ underlay_leaf_dict[item.key] }} {{ lookup('template', item.key ) }}"
            with_dict: "{{ underlay_leaf_dict }}"

          - name: Read template files for borderspine devices
            when: inventory_hostname in borderspine_group
            set_fact:
              underlay_block: "{{ underlay_block }} ! {{ underlay_borderspine_dict[item.key] }} {{ lookup('template', item.key ) }}"
            with_dict: "{{ underlay_borderspine_dict }}"

          - name: Read template files for spine devices
            when: inventory_hostname in spine_group
            set_fact:
              underlay_block: "{{ underlay_block }} ! {{ underlay_spine_dict[item.key] }} {{ lookup('template', item.key ) }}"
            with_dict: "{{ underlay_spine_dict }}"

          - name: Write to preview files
            include_tasks: ../subtasks/common_subtasks/subtask_write_to_preview_file.yml 

          rescue:
            - name: Record failure
              include_tasks: ../subtasks/common_subtasks/subtask_rescue_task.yml


- name: Display output file info
  hosts: localhost
  gather_facts: no
  run_once: True

  tasks:
    - debug:
        msg: 
        - "Please refer the following folders/files"
        - "'<hostname>-underlay.txt' in 'preview_files' folder for preview files"
        - "'underlay-err.log' in 'log_directory' folder for error informations if any"
