---
- name: Write DAG delete info to files in host_vars/delete_vars folder
  import_playbook: playbook_overlay_delete_generate.yml

- name: Automated VXLAN deployment with BGP EVPN L2/L3 underlay w/ Spine
  hosts: leaf
  gather_facts: no

  vars: 
    overlay_block: ""
    playbook_name: "overlay"
    playbook_mode: "-del"

    block_dict:
      '../templates/svi_create.j2': 'svi block'
      '../templates/nve_create.j2': 'nve block'
      '../templates/vlan_create.j2': 'vlan block' 
      '../templates/l2vpn_evpn_evi_create.j2': 'l2vpn evpn evi block'
      '../templates/vrf_definition.j2': 'vrf block'


  tasks:

          - name: Load variables from group_vars/delete_vars.yml file
            run_once: true
            include_vars: group_vars/delete_vars.yml
          
          - name: Load variables from files under group_vars/underlay_config.yml folder
            run_once: true
            include_vars: 
              file: group_vars/underlay_config.yml

          - name: Set "update_access_intf", "update_overlay_intf" value if absent
            run_once: true
            block:
            - name: Set "update_access_intf" value if absent
              when: update_access_intf is not defined
              set_fact:
                update_access_intf: false
                
            - name: Set "update_overlay_intf" value if absent
              when: update_overlay_intf is not defined
              set_fact:
                update_overlay_intf: false

          - name: Check whether host_vars/delete_vars/<hostname>.yml is present
            local_action: stat path=./host_vars/delete_vars/{{ inventory_hostname }}.yml
            register: file_state
            become: no 

          - name: Execute tasks if host_vars/delete_vars/<hostname>.yml is present
            when: file_state.stat.exists
            block:
            - name: Load variables from files under host_vars/delete_vars folder
              include_vars: host_vars/delete_vars/{{ inventory_hostname }}.yml

            - name: Read overlay template files
              set_fact:
                overlay_block: "{{ overlay_block }} ! {{ block_dict[item.key] }} {{ lookup('template', item.key) }}"
              with_dict: "{{ block_dict }}"

            - name: Read access interface template files
              when: update_access_intf == true
              set_fact:
                overlay_block: "{{ overlay_block }} ! access interfaces block {{ lookup('template', '../templates/access_interfaces.j2' ) }}"

            - name: Read overlay interface template files
              when: update_overlay_intf == true
              set_fact:
                overlay_block: "{{ overlay_block }} ! overlay interfaces block {{ lookup('template', '../templates/overlay_interfaces.j2' ) }}"

          - name: Write to preview files
            include_tasks: ../subtasks/common_subtasks/subtask_write_to_preview_file.yml


- name: Display output file info
  hosts: localhost
  gather_facts: no
  run_once: True

  tasks:
    - debug:
        msg: Please refer to <hostname>-delete.txt in 'preview_files' folder
