---

- name: Disable DHCP for EVPN overlay
  hosts: leaf
  gather_facts: no
  vars:
    action: 'delete'

  tasks:

            - name: Load vars from dhcp_delete_vars.yml
              run_once: true
              include_vars: 
                file: "./group_vars/dhcp_delete_vars.yml"
                name: dhcp_delete_vars

            - name: Run and parse "show run nve"
              ansible.utils.cli_parse:
                command: "show run nve"
                parser:
                  name: ansible.netcommon.pyats
                set_fact: overlay_dict

            - name: Collect "show run | sec dhcp"
              cli_command:
                command: show run | sec dhcp
              register: dhcp_output

            - name: Process DHCP data
              dhcp_del_preprocess: "{{ {
                  'overlay_dict': overlay_dict,
                  'to_del': dhcp_delete_vars,
                  'header_output': dhcp_output.stdout_lines } }}"
              register: dhcp_module_output

            - name: Include vars from dhcp output
              set_fact:
                "{{ item.key }}": "{{ item.value }}"
              with_dict: "{{ dhcp_module_output }}"

            - name: Apply configurations
              cli_config:
                config: "{{ lookup('template', '../templates/dhcp_overlay.j2') }}"
                diff_match: none
              register: result
