---

- name: Automated VXLAN deployment with BGP EVPN L2/L3 underlay w/ Spine
  hosts: all
  gather_facts: no
  vars_files:
    - "group_vars/overlay_db.yml"
  vars: 
    overlay_block: ""
    leaf_ol_dict:
      '../templates/vrf_definition.j2': 'vrf definition block'
      '../templates/bgp_l2vpn_ipv46_per_vrf.j2': 'bgp per vrf block'
      '../templates/vlan_create.j2': 'vlan block'
      '../templates/svi_create.j2': 'svi block'
      '../templates/l2vpn_evpn_global.j2': 'l2vpn evpn global block'
      '../templates/l2vpn_evpn_evi_create.j2': 'l2vpn evpn evi block'
      '../templates/evi_vni_vlan_stiching.j2': 'evi vni vlan stiching block'
      '../templates/overlay_interfaces.j2': 'overlay interface block'
      '../templates/nve_create.j2': 'nve block'

    common_ol_dict:
      '../templates/bgp_global.j2': 'bgp global block'
      '../templates/bgp_l2vpn_evpn_af.j2': 'bgp l2vpn evpn af block'

  tasks:

          - name: Read template files
            when: inventory_hostname in groups['leaf']
            set_fact:
              overlay_block: "{{ overlay_block }} ! {{ leaf_ol_dict[item.key] }} {{ lookup('template', item.key ) }}"
            with_dict: "{{ leaf_ol_dict }}"

          - name: Read template files - BGP related
            set_fact:
              overlay_block: "{{ overlay_block }} ! {{ common_ol_dict[item.key] }} {{ lookup('template', item.key ) }}"
            with_dict: "{{ common_ol_dict }}"

          - name: Render template files output
            set_fact:
              rendered: "{{  overlay_block | regex_replace('#jinja2: lstrip_blocks: \"True\", trim_blocks: \"True\"', '') | regex_replace('\\n(\\s+)','\n') | regex_replace('! ','\n! ') }}"

          - name: Copy configurations to respective file ( <hostname>-overlay.txt ) under 'preview_files' folder
            copy:
              dest: preview_files/{{inventory_hostname}}-overlay.txt
              content: "{{ rendered }}"

- name: Display output file info
  hosts: localhost
  gather_facts: no
  run_once: True

  tasks:
    - debug:
        msg: Please refer to <hostname>-overlay.txt in 'preview_files' folder
