---
- name: Write DAG incremental info to files in host_vars/inc_vars folder
  import_playbook: playbook_overlay_incremental_ipv6_generate.yml

- name: Automated VXLAN deployment with BGP EVPN L2/L3 underlay w/ Spine
  hosts: leaf
  gather_facts: no

  vars:
    svi_ipv6_block : "" 
    svi_ipv6_dict:
      '../templates/ipv6_incremental.j2': 'svi ipv6 block'


  tasks:

        - block:

          - name: Set playbook name and mode
            set_fact:
              playbook_name: "overlay_ipv6"
              playbook_mode: "-inc"

          - name: Check whether host_vars/ipv6_inc_vars/{{ inventory_hostname }}.yml is present
            local_action: stat path=./host_vars/ipv6_inc_vars/{{ inventory_hostname }}.yml
            register: file_state
            become: no 

          - name: Executing tasks if host_vars/ipv6_inc_vars/{{ inventory_hostname }}.yml is present
            when: file_state.stat.exists and inventory_hostname in groups['leaf']
            block:
            - name: Load variables from files under host_vars/ipv6_inc_vars folder
              include_vars: host_vars/ipv6_inc_vars/{{ inventory_hostname }}.yml
            
          - name: SVI configuration
            when: inventory_hostname in groups['leaf']
            set_fact:
              svi_ipv6_block: "{{ svi_ipv6_block }} ! {{ svi_ipv6_dict[item.key] }} {{ lookup('template', item.key ) }}"
            with_dict: "{{ svi_ipv6_dict }}"

          - name: Render template files output
            set_fact:
              rendered: "{{  svi_ipv6_block | regex_replace('#jinja2: lstrip_blocks: \"True\", trim_blocks: \"True\"', '') | regex_replace('\\n(\\s+)','\n') | regex_replace('! ','\n! ') }}"

          - name: Copy configurations to respective file ( <hostname>-inc-overlay_ipv6.txt ) under 'preview_files' folder
            copy:
              dest: preview_files/{{inventory_hostname}}{{ playbook_mode }}-{{ playbook_name }}.txt
              content: "{{ rendered }}"
              
          - name: Clearing configurations in preview_files/( <hostname>-inc-overlay_ipv6.txt ) if device config is skipped  
            when: not file_state.stat.exists
            copy:
              dest: preview_files/{{inventory_hostname}}{{ playbook_mode }}-{{ playbook_name }}.txt
              content: ""

          rescue:
            - name: Record failure
              include_tasks: ../subtasks/common_subtasks/subtask_rescue_task.yml


- name: Display output file info
  hosts: localhost
  gather_facts: no
  run_once: True

  tasks:
    - debug:
        msg: 
        - "Please refer the following folders/files"
        - "'<hostname>-inc-overlay_ipv6.txt' in 'preview_files' folder for preview files"
        - "'overlay_ipv6-inc-err.log' in 'log_directory' folder for error informations if any"
