---

- name: Automated VXLAN deployment with BGP EVPN L2/L3 underlay w/ Spine
  hosts: leaf
  gather_facts: no

  vars:
    input_vars_path: './'
    acc_inc: false
    
    info_dict:
      access:
        key_name: 'access_vlan'
      trunks:
        key_name: 'trunk_vlan_list'


  tasks:

        - block:

          - name: Set playbook name and mode
            set_fact:
              playbook_name: "access_intf"
              playbook_mode: ""

          - name: Set playbook mode
            when: acc_inc == true
            set_fact:
              playbook_mode: "-inc"

          # leaf_group is defined in this subtask
          - name: Get inventory groups
            include_tasks: ../subtasks/common_subtasks/subtask_get_inventory_group.yml

          - name: Configure access interfaces on leaf-s
            when: inventory_hostname in leaf_group
            block:
      
            - name: Load variables from access interface input file if present
              block:

              - name: Check whether host_vars/access_intf/<hostname>.yml is present
                local_action: stat path="{{ input_vars_path }}host_vars/access_intf/{{ inventory_hostname }}.yml"
                register: access_intf_file_state
                become: no 

              - name: Load variables from host_vars/access_intf/<hostname>.yml if present
                include_vars:
                  file: "{{ input_vars_path }}host_vars/access_intf/{{ inventory_hostname }}.yml"
                  name: get_Leaf_vars
                when: access_intf_file_state.stat.exists

            # Following tasks are skippped if host_vars/access_intf/<hostname>.yml is not present

            - name: Process interfaces
              when: (get_Leaf_vars is defined) and (get_Leaf_vars.access_interfaces is defined)
              block:

              - set_fact:
                  task_to_execute: "../subtasks/access_intf_subtasks/subtask_acc_intf_commit.yml"

              - name: Process trunk interfaces
                when: get_Leaf_vars.access_interfaces.trunks is defined
                include_tasks: ../subtasks/access_intf_subtasks/subtask_acc_intf_trunk.yml

              - name: Process access interfaces
                when: get_Leaf_vars.access_interfaces.access is defined
                include_tasks: ../subtasks/access_intf_subtasks/subtask_acc_intf_access.yml

          rescue:
            - name: Record failure
              include_tasks: ../subtasks/common_subtasks/subtask_rescue_task.yml


- name: Display output file info
  hosts: localhost
  gather_facts: no
  run_once: True
  vars:
    playbook_mode: ''

  tasks:
    - debug:
        msg: 
        - "Please refer the following folders/files"
        - "'access_intf{{ playbook_mode }}-err.log' in 'log_directory' folder for error informations if any"
