---

- name: Automated VXLAN deployment with BGP EVPN L2/L3 underlay w/ Spine
  hosts: all
  gather_facts: no
  vars:
    underlay_block: ""
    underlay_dict:
      '../templates/hostname.j2': 'hostname block'
      '../templates/global_routing.j2': 'global routing block'
      '../templates/underlay_interfaces.j2': 'underlay interface block'
      '../templates/ospf_interfaces.j2': 'ospf interface block'
      '../templates/pim_interfaces.j2': 'pim interface block'
      '../templates/pim_rp.j2': 'pim rp block'

  tasks:

          - name: Read template files
            set_fact:
              underlay_block: "{{ underlay_block }} ! {{ underlay_dict[item.key] }} {{ lookup('template', item.key ) }}"
            with_dict: "{{ underlay_dict }}"

          - name: Read MSDP peering template file
            when: inventory_hostname in groups['spine']
            set_fact:
              underlay_block: "{{ underlay_block }} ! MSDP peering block {{ lookup('template', '../templates/msdp_peering.j2' ) }}"

          - name: Render template files output
            set_fact:
              rendered: "{{ underlay_block | regex_replace('#jinja2: lstrip_blocks: \"True\", trim_blocks: \"True\"', '') | regex_replace('\\n(\\s+)','\n') | regex_replace('! ','\n! ') }}"

          - name: Copy configurations to the respective file ( <hostname>-underlay.txt ) under 'preview_files' folder
            copy:
              dest: preview_files/{{inventory_hostname}}-underlay.txt
              content: "{{ rendered }}"

- name: Display output file info
  hosts: localhost
  gather_facts: no
  run_once: True

  tasks:
    - debug:
        msg: Please refer to <hostname>-underlay.txt in 'preview_files' folder
