---

- name: Initialising variable for leaf-s
  hosts: leaf
  gather_facts: no
  tasks:    
          - set_fact:
              incremental: true

- name: Initialising variable for localhost
  hosts: localhost
  gather_facts: no
  tasks:    
          - set_fact:
              incremental: true

- name: Import tasks from playbook_access_add_commit.yml
  import_playbook: playbook_access_add_commit.yml
