---

- name: Automated VXLAN deployment with BGP EVPN L2/L3 underlay w/ Spine
  hosts: leaf
  gather_facts: no 

  tasks:
          - name: Cleanup host_vars/ipv6_delete_vars dir
            run_once: true
            file:
              state: "{{ item }}"
              path: "host_vars/ipv6_delete_vars"
            with_items:
              - absent
              - directory
              
          - name: Collect vars from overlay_db.yml
            run_once: true
            include_vars:
              file: group_vars/overlay_db.yml
              name: to_compare
          
          - name: Collect vars from ipv6_delete_vars.yml
            run_once: true
            include_vars:
              file: group_vars/ipv6_delete_vars.yml
              name: user_input

          - name: Collect "show run nve"
            cli_command:
              command: show run nve
            register: command_output
            
          - name: Collect vars from hostvars leafs
            run_once: true
            include_vars:
              file: host_vars/node_vars/{{ inventory_hostname }}.yml
              name: hostvars_leaf_data
                
          - name: Process data
            delete_ipv6:
              hostvars: "{{ command_output.stdout_lines }}"
              leaf_data:  "{{ hostvars_leaf_data }}"
              overlay_db: "{{ to_compare }}"
              userinput: "{{ user_input }}"
            register: module_output
              
          - name: Copying configurations to the repective files ( <hostname>.yml ) under host_vars/ipv6_delete_vars folder
            when: module_output['yaml'] != '{}\n'
            copy:
              dest: host_vars/ipv6_delete_vars/{{ inventory_hostname }}.yml
              content: "{{ module_output['yaml'] }}"
