- name: Initialising variable for leaf-s
  hosts: leaf
  gather_facts: no
  tasks:    
          - set_fact:
              action: 'delete'

- name: Import tasks from playbook_dhcp_add_commit.yml
  import_playbook: playbook_dhcp_add_commit.yml
