---

- name: Automated VXLAN deployment with BGP EVPN L2/L3 underlay w/ Spine
  hosts: all
  gather_facts: no
  vars:
    incremental_run: false

  tasks:

          - name: load variables
            include_vars: incremental_vars.yml

          - name: check if full execution is needed
            set_fact: 
              incremental_run: true
            when: (vrf_cli is defined) or (vlan_cli is defined) or (svi_cli is defined) or (ovrl_intf_cli is defined)
          
          - name: Configuring vrf definition
            when: (inventory_hostname in groups['leaf']) and ((incremental_run == true and vrf_cli is defined) or (incremental_run == false))
            cli_config:
              config: "{{ lookup('template', '../templates/vrf_definition.j2') }}"
              diff_match: none 
            register: result

          - name: Configuring neighbors globally for BGP
            cli_config:
              config: "{{ lookup('template', '../templates/bgp_global.j2') }}"
            register: result
            when: incremental_run == false
          
          - name: Activating BGP neighbor under L2VPN/EVPN AFI/SAFI
            cli_config:
              config: "{{ lookup('template', '../templates/bgp_l2vpn_evpn_af.j2') }}"
              diff_match: none 
            register: result
            when: incremental_run == false

          - name: Activating BGP for AF(ipv4/ipv6) per vrf
            when: (inventory_hostname in groups['leaf']) and ((incremental_run == true and vrf_cli is defined) or (incremental_run == false))
            cli_config:
              config: "{{ lookup('template', '../templates/bgp_l2vpn_ipv46_per_vrf.j2') }}"
              diff_match: none 
            register: result
          
          - name: Access/Core VLAN creating
            when: (inventory_hostname in groups['leaf']) and ((incremental_run == true and vlan_cli is defined) or (incremental_run == false))
            cli_config:
              config: "{{ lookup('template', '../templates/vlan_create.j2') }}"
              diff_match: none 
            register: result

          - name: VLAN to port assignment
            when: (inventory_hostname in groups['leaf']) and ((incremental_run == true and access_inft_cli is defined) or (incremental_run == false)) 
            cli_config:
              config: "{{ lookup('template', '../templates/access_interfaces.j2') }}"
              diff_match: none 
            register: result

          - name: SVI creation
            when: (inventory_hostname in groups['leaf']) and ((incremental_run == true and svi_cli is defined) or (incremental_run == false)) 
            cli_config:
              config: "{{ lookup('template', '../templates/svi_create.j2') }}"
              diff_match: none 
            register: result            
          
          - name: Global L2VPN EVPN configuration
            when: (inventory_hostname in groups['leaf']) and (incremental_run == false)
            cli_config:
              config: "{{ lookup('template', '../templates/l2vpn_evpn_global.j2') }}"
              diff_match: none 
            register: result

          - name: EVPN EVI creation
            when: (inventory_hostname in groups['leaf']) and ((incremental_run == true and vlan_cli is defined) or (incremental_run == false))
            cli_config:
              config: "{{ lookup('template', '../templates/l2vpn_evpn_evi_create.j2') }}"
              diff_match: none 
            register: result
          
          - name: EVI/VNI/VLAN stiching
            when: (inventory_hostname in groups['leaf']) and ((incremental_run == true and vlan_cli is defined) or (incremental_run == false))
            cli_config:
              config: "{{ lookup('template', '../templates/evi_vni_vlan_stiching.j2') }}"
              diff_match: none 
            register: result

          - name: Overlay Interface Create
            when: (inventory_hostname in groups['leaf']) and ((incremental_run == true and ovrl_intf_cli is defined) or (incremental_run == false))
            cli_config:
              config: "{{ lookup('template', '../templates/overlay_interfaces.j2') }}"
              diff_match: none 
            register: result

          - name: NVE interface configuration
            when: (inventory_hostname in groups['leaf']) and ((incremental_run == true and vlan_cli is defined) or (incremental_run == false))
            cli_config:
              config: "{{ lookup('template', '../templates/nve_create.j2') }}"
              diff_match: none 
            register: result       

          - name: Pause for 60 seconds for convergence  
            wait_for:
              delay: 60
              timeout: 0
            when: incremental_run == false
