hostname: 'Leaf-02'

routing:
  ipv4_multi: 'yes'

interfaces:

  Loopback0:
    name: 'Routing Loopback'
    ip_address: '172.16.255.4'
    subnet_mask: '255.255.255.255'
    loopback: 'yes'
    pim_enable: 'yes'

  Loopback1:
    name: 'NVE Loopback'
    ip_address: '172.16.254.4'
    subnet_mask: '255.255.255.255'
    loopback: 'yes'
    pim_enable: 'yes'

  GigabitEthernet1/0/34:
    name: 'Backbone interface to Spine-01'
    ip_address: '172.16.14.4'
    subnet_mask: '255.255.255.0'
    loopback: 'no'
    pim_enable: 'yes'

  GigabitEthernet1/0/35:
    name: 'Backbone interface to Spine-02'
    ip_address: '172.16.24.4'
    subnet_mask: '255.255.255.0'
    loopback: 'no'
    pim_enable: 'yes' 

ospf:
  router_id: '172.16.255.4'

pim:
  rp_address: '172.16.255.255'

bgp:
  as_number: '65001'
  router_id: 'Loopback0'
  neighbors:
    '172.16.255.1':
     peer_as_number: '65001'
     source_interface: 'Loopback0'
    
    '172.16.255.2':
     peer_as_number: '65001'
     source_interface: 'Loopback0'

#layer 3 interface
overlay_interfaces:
  Loopback11:
    name: 'Vrf Loopback'
    ip_address: '10.2.11.11'
    subnet_mask: '255.255.255.0'
    loopback: 'yes'
    vrf: 'green'

  Loopback12:
    name: 'Vrf Loopback'
    ip_address: '10.2.12.12'
    subnet_mask: '255.255.255.0'
    loopback: 'yes'
    vrf: 'blue'
  
  Loopback901:
    name: 'Vrf Loopback'
    ip_address: '10.1.255.2'
    subnet_mask: '255.255.255.255'
    ipv6:
      - 'FC00:1:255::2/128'
    loopback: 'yes'
    pim_enable: 'yes'
    vrf: 'green'

  Loopback902:
    name: 'Vrf Loopback'
    ip_address: '10.2.255.2'
    subnet_mask: '255.255.255.255'
    ipv6:
      - 'FC00:2:254::2/128'
    loopback: 'yes'
    pim_enable: 'yes'
    vrf: 'blue'
