# This is the input file for playbook_overlay_delete_preview.yml and playbook_overlay_delete_commit.yml
#
# List the vlans to be deleted under 'vlans' keyword
# The keyword 'update_access' when set to true removes the related VLANs from the interfaces
#
#
# ______________________________________________
# __________ EXAMPLE SCENARIOS _________________
# ______________________________________________
#
# Example 1: Deletes 101 and 102 vlans and removes the respective VLANs from the access interfaces
# 
#   vlans:
#      - 101             <--------- deletes 101 and 102 VLANs
#      - 102
#
#   update_access_intf: true   <--------- removes the respective VLANs from the access interfaces
#
#
# Example 2: Deletes all the VLANs and makes NO changes to the access interfaces
#
#   vlans:
#      - all               <--------- deletes all the VLANs
# 
#   update_access_intf: false   <--------- makes NO changes to the access interfaces
#
# ______________________________________________
# ______________________________________________
# ______________________________________________


 vlans:
  - 104

 update_access_intf: true
