hostname: 'Spine-01'

routing:
 ipv4_uni: 'yes'
 ipv4_multi: 'yes'

interfaces:

  Loopback0:
    name: 'Routing Loopback'
    ip_address: '172.16.255.1'
    subnet_mask: '255.255.255.255'
    loopback: 'yes'
    pim_enable: 'no'

  Loopback1:
    name: 'MSDP Loopback'
    ip_address: '172.16.254.1'
    subnet_mask: '255.255.255.255'
    loopback: 'yes'
    pim_enable: 'yes'
  
  Loopback2:
    name: 'AnycastRP Loopback'
    ip_address: '172.16.255.255'
    subnet_mask: '255.255.255.255'
    loopback: 'yes'
    pim_enable: 'yes'

  GigabitEthernet1/0/1:
    name: 'Backbone interface to Leaf-01'
    ip_address: '172.16.13.1'
    subnet_mask: '255.255.255.0'
    loopback: 'no'
    pim_enable: 'yes'

  GigabitEthernet1/0/2:
    name: 'Backbone interface to Leaf-02'
    ip_address: '172.16.14.1'
    subnet_mask: '255.255.255.0'
    loopback: 'no'
    pim_enable: 'yes' 

ospf:
  router_id: '172.16.255.1'

pim:
  rp_address: '172.16.255.255'

msdp:
 '1':
    peer_ip: '172.16.254.2'
    source_interface: 'Loopback1'
    remote_as: '65001'
    
bgp:
  as_number: '65001'
  router_id: 'Loopback0'
  neighbors:
    '172.16.255.2':
     peer_as_number: '65001'
     source_interface: 'Loopback0'
     rrc: 'yes'

    '172.16.255.3':
     peer_as_number: '65001'
     source_interface: 'Loopback0'
     rrc: 'yes'
     
    '172.16.255.4':
     peer_as_number: '65001'
     source_interface: 'Loopback0'
     rrc: 'yes'