# List the playbooks to be run under 'playbooks_to_run' key
# Enter the name of the playbook(excluding auth playbooks) folder under 'playbook_folder' key
# By default, playbook_folder is set to 'dag'
# Playbooks are executed in the same order as listed

playbooks_to_run:
  - underlay
  - overlay
  - access_add
  - dhcp
  - trm_overlay

#playbook_folder: 'dag'