# ipv6_delete:
# ==================
# This is the input file for playbook_overlay_delete_ipv6_preview.py and playbook_overlay_delete_ipv6_commit.py
# Please find below the examples of declaring the respective vrf's under dag for ipv6_delete
# 1) with all vrf's 
#      ..........................................
#      .        l3vni:              .
#      .          - all       -------------> deletes ipv6 for all the vrf's that are provisioned in the device                .    .
#      ..........................................
# 2) with two vrf's 
#      ..........................................
#      .        l3vni:              .
#      .          - green     -------------> deletes ipv6 for green and blue vrf's that are provisioned n the device
#      .          - blue                       .    .
#      ..........................................
#
# ______________________________________________
# ______________________________________________
# ______________________________________________

l3vni:
   - all
