---

- name: Automated VXLAN deployment with BGP EVPN L2 underlay w/ Spine
  hosts: leaf
  gather_facts: no
  vars:
    update_acc_intf: false
    
  tasks:
          - name: Load variables from group_vars/delete_vars.yml file
            run_once: true
            include_vars:
              file: group_vars/delete_vars.yml
              name: to_del

          - name: Collect "show run nve"
            cli_command:
              command: show run nve
            register: nve_output

          - name: Add "show run nve" output to dictionary
            set_fact: 
              command_output: "{{ { 'run_nve' : nve_output.stdout_lines} }}"

          - name: Get "update_access" value if present in group_vars/delete_vars.yml
            when: to_del['update_access'] is defined
            set_fact:
              update_acc_intf: "{{ to_del['update_access'] }}"

          - name: Collect and add interface information to dictionary
            when: update_acc_intf == true
            block:
              - name: Collect "show run | section ^interface"
                cli_command:
                  command: show run | section ^interface
                register: interface_output

              - name: Add "show run | section ^interface" output to dictionary
                set_fact: 
                  command_output: "{{ command_output | combine ( {'intf_sec' : interface_output.stdout_lines} ) }}"

          - name: Process collected CLIs' output
            parser_to_delete_yaml:
              hostvars: "{{ command_output }}"
              toDel: "{{ to_del }}"
            register: module_output
             
          - name: Copying configurations to the repective files ( <hostname>.yml ) under host_vars/delete_vars folder
            when: module_output['yaml'] != '{}\n'
            copy:
              dest: host_vars/delete_vars/{{ inventory_hostname }}.yml
              content: "{{ module_output['yaml'] }}"
