---
- name: Write l2vni incremental info to files in host_vars/inc_vars folder
  import_playbook: playbook_overlay_incremental_generate.yml

- name: Automated VXLAN deployment with BGP EVPN L2 underlay w/ Spine
  hosts: all
  gather_facts: no

  vars_files:
    - "group_vars/overlay_db.yml"

  vars:
    incremental_run: false
    input_vars_path: "./"
    
    vlan_dict:
      '../templates/vlan_create.j2': 'vlan block'
      '../templates/l2vpn_evpn_evi_create.j2': 'l2vpn evpn evi create block'
      '../templates/evi_vni_vlan_stiching.j2': 'evi vni vlan stiching block'
      '../templates/nve_create.j2': 'nve create block'
    l2vpn_evpn_global_dict:
      '../templates/l2vpn_evpn_global.j2': 'l2vpn evpn global block'
    common_dict:
      '../templates/bgp_global.j2': 'bgp global block'
      '../templates/bgp_l2vpn_evpn_af.j2': 'bgp l2vpn evpn af block'

  tasks:

        - block:

          - name: Set playbook name and mode
            set_fact:
              playbook_name: "overlay"
              playbook_mode: "-inc"

          - name: Load vars from node_vars/<host>.yml input file
            include_vars: 
              file: "{{ input_vars_path }}host_vars/node_vars/{{ inventory_hostname }}.yml"

          - name: Load vars from group_vars/underlay_config file
            run_once: true
            include_vars:
              file: "group_vars/underlay_config.yml"
              
          - name: Check whether host_vars/inc_vars/{{ inventory_hostname }}.yml is present
            local_action: stat path=./host_vars/inc_vars/{{ inventory_hostname }}.yml
            register: file_state
            become: no 
            
          - name: Executing tasks if host_vars/inc_vars/{{ inventory_hostname }}.yml is present
            when: file_state.stat.exists and inventory_hostname in groups['leaf']
            block:
            - name: Load variables from files under host_vars/inc_vars folder
              include_vars: host_vars/inc_vars/{{ inventory_hostname }}.yml

          - name: Check if full execution is needed
            set_fact: 
              incremental_run: true
            when: (vlan_cli is defined) or (access_intf_cli is defined)
            
          - name: VLAN configuration
            when: (inventory_hostname in groups['leaf']) and ((incremental_run == true and vlan_cli is defined)) 
            cli_config:
              config: " {{ lookup('template', item.key) }} "
              diff_match: none 
            register: result
            with_dict: "{{ vlan_dict }}"

          - name: Global L2VPN EVPN configuration
            when: (inventory_hostname in groups['leaf']) and (incremental_run == false)
            cli_config:
              config: " {{ lookup('template', item.key) }} "
              diff_match: none 
            register: result
            with_dict: "{{ l2vpn_evpn_global_dict }}"
            
          - name: BGP neighbors configuration
            when: incremental_run == false
            cli_config:
              config: " {{ lookup('template', item.key) }} "
              diff_match: none 
            register: result
            with_dict: "{{ common_dict }}"

          - name: Pause for 60 seconds for convergence  
            wait_for:
              delay: 60
              timeout: 0
            when: incremental_run == false

          rescue:
            - name: Record failure
              include_tasks: ../subtasks/common_subtasks/subtask_rescue_task.yml


- name: Display output file info
  hosts: localhost
  gather_facts: no
  run_once: True

  tasks:
    - debug:
        msg: 
        - "Please refer the following folders/files"
        - "'overlay-inc-err.log' in 'log_directory' folder for error informations if any"
